### ISSUE TITLE
PAGService can't send any messages to UsersMS though event-bus on the docker infrastructure. 

### ISSUE THREAD

**Issue by romalev** [romalev/yummy-tweets#17]
Clearly the networking issue. Please see : 
* https://groups.google.com/forum/#!msg/vertx/_2MzDDowMBM/nFoI_k6GAgAJ
* https://stackoverflow.com/questions/39812848/how-do-i-configure-vert-x-event-bus-to-work-across-cluster-of-docker-containers

Stacktrace: 
<pre>2018-04-03 13:47:17 [vert.x-eventloop-thread-3] DEBUG c.y.a.g.PublicApiGatewayEbService::createUser - Creating a user by sending the message : UserCreateCommand{headers={}, correlationId='0ac273ed-c72d-4a2d-be89-fa59860be3e1', commandName='UserCreateCommand', firstName='roman', lastName='lev', company='realdolmen', email='realdolmen'} to: users.create.message.channel.
2018-04-03 13:47:17 [vert.x-eventloop-thread-3] DEBUG i.v.c.e.i.clustered.ConnectionHolder::writeMessage - Not connected to server localhost:40209 - starting queuing
2018-04-03 13:47:17 [vert.x-eventloop-thread-3] WARN  i.v.c.e.i.clustered.ConnectionHolder::lambda$connect$0 - Connecting to server localhost:40209 failed
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:40209
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
        ... 11 common frames omitted
2018-04-03 13:47:17 [vert.x-eventloop-thread-3] DEBUG i.v.c.e.i.clustered.ConnectionHolder::close - Cluster connection closed for server localhost:40209
2018-04-03 13:47:18 [vert.x-eventloop-thread-3] TRACE c.y.a.g.f.UserCreateDefaultFallback::apply - Applying UserCreateDefaultFallback.
</pre>

**Comment by romalev** [comment]
Fixed in https://github.com/romalev/yummy-tweets/pull/21
